# Generated by Django 4.1.3 on 2022-11-25 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.band', verbose_name='band'),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_reviews', to='music.album', verbose_name='album'),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_reviews', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='albumreviewcomment',
            name='album_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_review_comments', to='music.albumreview', verbose_name='album_review'),
        ),
        migrations.AlterField(
            model_name='albumreviewcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_review_comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='albumreviewlike',
            name='album_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_review_likes', to='music.albumreview', verbose_name='album_review'),
        ),
        migrations.AlterField(
            model_name='albumreviewlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_review_likes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.album', verbose_name='album'),
        ),
    ]
