# Generated by Django 4.1.3 on 2022-11-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_band_alter_albumreview_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreviewcomment',
            name='album_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.albumreview', verbose_name='album_review'),
        ),
        migrations.AlterField(
            model_name='albumreviewlike',
            name='album_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music.albumreview', verbose_name='album_review'),
        ),
    ]
